"""empty message

Revision ID: 3411b76a8b6b
Revises: 
Create Date: 2022-06-30 17:36:26.698702

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3411b76a8b6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('captcha', sa.String(length=10), nullable=False),
                    sa.Column('send_time', sa.Integer(), nullable=False),
                    sa.Column('valid_time', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('captcha'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('users_information',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(length=20), nullable=False),
                    sa.Column('password', sa.String(length=220), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('regits_time', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('question',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=200), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['users_information.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('users_information')
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
