"""empty message

Revision ID: 571c39bd0499
Revises: 3bbb4cc49393
Create Date: 2022-08-17 11:27:43.569631

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '571c39bd0499'
down_revision = '3bbb4cc49393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.Column('create_time', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['author_id'], ['users_information.id'], ),
                    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    # ### end Alembic commands ###
