"""empty message

Revision ID: 6cc1f2bd68e9
Revises: 45d79f972f71
Create Date: 2022-06-11 11:58:10.099763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc1f2bd68e9'
down_revision = '45d79f972f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=220), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('regits_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_information')
    # ### end Alembic commands ###
